import React, { useEffect, useState } from 'react';
import Card from '../components/Card';
import Loader from '../components/loader';

const RenderCards = ({ data }) => {
    if (data?.length > 0) {
      return (
        data.map((post) => <Card key={post._id} {...post} />)
      );
    }
    else{
        return <h2 style={{margin:'10px auto'}}>No Post Found</h2>
    }
  };

function Home() {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('');
    const [searchTimeout, setSearchTimeout] = useState(null);
    const [searchedResults, setSearchedResults] = useState(null);

    const fetchPost = async() => {
        setLoading(true);
        try{
            const response = await fetch('http://localhost:786/api/v1/get-all',
            {
                method:'GET',
                headers:{'Content-Type': 'application/json'},
            })

            if(response.ok){
                const result = await response.json();

                setAllPosts(result.data);
            }
        }
        catch(err){
            alert(err);
        }
        finally{
            setLoading(false);
        }
    }

    useEffect(() => {
        fetchPost();
    },[]);

    const handleSearchText=(e)=>{
        clearTimeout(searchTimeout);
        setSearchText(e.target.value);

        setSearchTimeout(
            setTimeout(() => {
                const searchResult = allPosts.filter((item) => item.prompt.toLowerCase().includes(searchText.toLowerCase()));
                setSearchedResults(searchResult);
            }, 1000)
        );
    }
    
  return (
    <div style={{margin:'0 0 40px 0'}}>
        <div className='community_showcase'>
            <h1>The Community Showcase</h1>
            <p>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI.</p>
        </div>

        <div className='search_bar'>
            <input type='text' placeholder='Search a post..' onChange={handleSearchText}/>
        </div>

        <div className='images_grid'>
            {
                loading 
                ?
                <Loader text="Loading Posts..." />
                :
                searchText ?
                <RenderCards data={searchedResults}/>
                :
                <RenderCards data={allPosts}/>
            }
        </div>
    </div>
  )
}

export default Home